project_name: money-tree
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: VageLO <48802151+VageLO@users.noreply.github.com>
  description: Money-tree.
  homepage: https://github.com/VageLO/money-tree
  license: MIT
