project_name: money-tree
before:
    hooks:
        - go mod init github.com/VageLO/money-tree
        - go mod tidy
builds:
    binary: money_tree
    goos:
        - windows
        - linux
    env:
        - CGO_ENABLED=1
nfpms:
- maintainer: VageLO
  description: Money tree
  homepage: https://github.com/VageLO/money-tree
  license: MIT
