---

project_name: money-tree

before:
    hooks:
        - go mod init github.com/VageLO/money-tree
        - go mod tidy

builds:
    env: [CGO_ENABLED=1]
    goos:
        - linux
    goarch:
        - amd64
        #- 386
    overrides:
        goos: linux
        goarch: amd64
        env:
            - CC=gcc

checksum:
    name_template: "{{ .ArtifactName }}_checksums.txt"

nfpms:
- maintainer: VageLO
  description: Money tree
  homepage: https://github.com/VageLO/money-tree
  license: MIT
