before:
  hooks:
    - go mod init github.com/VageLO/money-tree
    - go mod tidy

builds:
  - binary: money_tree
    goos:
      - windows
      - linux
    goarch:
      - amd64
    goarm:
      - 6
      - 7