project_name: money-tree
before:
  hooks:
    - go env -w CGO_ENABLED=1
    - go mod init github.com/VageLO/money-tree
    - go mod tidy
builds:
  - binary: money_tree
    goos:
      - windows
      - linux
nfpms:
- maintainer: VageLO
  description: Money tree
  homepage: https://github.com/VageLO/money-tree
  license: MIT
