# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build

on:
  push:
    tags:
      - "*"

jobs:
  release-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install cross-compiler
        run: sudo apt-get -y install gcc-aarch64-linux-gnu

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: true
        
      - name: Clean
        run: go clean -modcache
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --config .goreleaser-linux.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-windows-binary:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: Install cross-compiler
          run: sudo apt-get -y install gcc-aarch64-linux-gnu

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.20'
            cache: true
          
        - name: Clean
          run: go clean -modcache
          
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            version: latest
            args: release --config .goreleaser-windows.yml --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
